baseURL = "https://sambriggs.dev/"
languageCode = "en-uk"
defaultContentLanguage = "en"
isMultilingual = false
title = "Sam Briggs"
theme = "hugo-theme-sam"
googleAnalytics = "UA-157531859-1"

[params]
    dateform = "2 Jan 2006"
    homepage = "Home" # What to call the home page link
    footerText = "The personal blog of Sam Briggs, just another nerd."

    # Metadata for Open Graph and Twitter
    description = "The personal blog of Sam Briggs, just another nerd."
    title = "Sam Briggs"
