baseURL = "https://sambriggs.dev/"
languageCode = "en-gb"
defaultContentLanguage = "en"
isMultilingual = false
title = "Sam Briggs [software developer]"
theme = "hugo-theme-sam"
googleAnalytics = "UA-157531859-1"

[params]
    dateform = "2 Jan 2006"
    homepage = "home" # What to call the home page link
    footerText = "The software blog of Sam Briggs, just another nerd."

    # Metadata for Open Graph and Twitter
    description = "The software blog of Sam Briggs, just another nerd."
    title = "Sam Briggs"

[[params.mainMenu]]
    link = "/about"
    text = "about"

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "https://github.com/briggySmalls"
    text = "github"
