version: 2

jobs:
  # Job to check markdown
  lint-markdown:
    docker:
      - image: node:latest
    steps:
      - run:
          name: Install markdownlint
          command: npm install -g markdownlint-cli
      - checkout
      - run:
          name: Run linter
          command: markdownlint content archetypes
  # Job to generate content
  generate:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/hugo
    steps:
      - run:
          name: Install graphviz
          command: sudo apt-get update && sudo apt-get install -y graphviz plantuml
      - run:
          name: Install archie
          command: go get github.com/briggysmalls/archie/cli/archie
      - checkout
      - run:
          name: Generate images
          command: ./generate.sh
      - persist_to_workspace:
          root: ./static
          paths: _gen
  # Job to build the site
  build:
    docker:
      - image: cibuilds/hugo:0.69.0
    working_directory: ~/hugo
    steps:
      - run:
          name: Set dynamic environment variables
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              echo 'export HUGO_ENV=production' >> $BASH_ENV
            else
              echo 'export HUGO_ENV=development' >> $BASH_ENV
            fi;
            source $BASH_ENV
      # checkout the repository
      - checkout
      - run:
          name: Install git submodules
          command: git submodule sync && git submodule update --init
      - run:
          name: Install apt packages
          command: sudo apt-get update && sudo apt-get install -y npm tree
      - run:
          name: Install node dependencies
          command: sudo npm install -g postcss-cli autoprefixer
      # Attach generated source
      - attach_workspace:
          at: static
      - run:
          name: Build with Hugo
          command: hugo -v
      - run:
          name: Show build output
          command: tree ./public
      - persist_to_workspace:
          root: .
          paths: public
  # Job to test the site
  test-html:
    docker:
      - image: cibuilds/hugo:0.69.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: test HTML files
          command: htmlproofer ./public --url-ignore /https:\/\/www\.amazon\.co\.uk/ --allow-hash-href --check-html
  # Job to deploy to Github pages
  deploy:
    docker:
      - image: node:8.10.0  # We need this for the javascript tool
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: npm install -g --silent gh-pages@2.0.1
      - run:
          name: Configure git
          command: |
            git config user.email "ci-build@sambriggs.dev"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "90:0b:12:c9:19:f0:29:a8:61:f5:39:8b:5d:d1:51:94"
      - run:
          name: Add CNAME record
          command: echo 'sambriggs.dev' >> ./public/CNAME
      - run:
          name: Disable jekyll processing
          command: touch ./public/.nojekyll
      - run:
          name: Deploy to gh-pages branch
          command: gh-pages --dotfiles --dist ./public --message "[ci skip] Deploy updates"

workflows:
  version: 2
  main:
    jobs:
      - lint-markdown
      - generate
      - build:
          requires:
            - generate
      - test-html:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
            - lint-markdown
            - test-html
